# Generated by Django 5.1.7 on 2025-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_chat_telegram_bot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
