services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - web

  web:
    image: ${DOCKER_HUB_USERNAME}/habit_tracker:${IMAGE_TAG}
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    command: bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    restart: on-failure
    depends_on:
      - db
      - celery-beat

  db:
    image: postgres:17.4
    environment:
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis
    expose:
      - 6379
    environment:
      TZ: Europe/Moscow
    volumes:
      - redis_volume:/data

  celery:
    image: ${DOCKER_HUB_USERNAME}/habit_tracker:${IMAGE_TAG}
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    env_file:
      - .env
    command: "poetry run celery -A config worker -l INFO"
    depends_on:
      - redis

  celery-beat:
    build: ${DOCKER_HUB_USERNAME}/habit_tracker:${IMAGE_TAG}
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    env_file:
      - .env
    command: "poetry run celery -A config beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - celery
      - db

  telegram-bot:
    build: ${DOCKER_HUB_USERNAME}/habit_tracker:${IMAGE_TAG}
    environment:
      DB_HOST: db
    env_file:
      - .env
    command: poetry run python manage.py runtelegrambot


networks:
  default:


volumes:
  media_volume:
  static_volume:
  postgres_volume:
  redis_volume:
