# Generated by Django 5.1.7 on 2025-03-15 17:55

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "time_to_complete",
                    models.TimeField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.time(0, 2)
                            )
                        ],
                    ),
                ),
                ("action", models.TextField(blank=True, max_length=1000, null=True)),
                ("reward", models.CharField(blank=True, max_length=250, null=True)),
                ("is_joy", models.BooleanField()),
                ("period_in_days", models.IntegerField(default=1)),
                ("notification_time", models.TimeField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "joy_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
