name: Deploy by pull request

on: [push]
#  workflow_run:
#    workflows: ["Test code by Push"]
#    types:
#      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:


  deploy:
    runs-on: ubuntu-latest

    steps:


