name: Test code by Push

on: [push]

test:
  runs-on: ubuntu-latest

  services:
    postgres:
      image: postgres:17.4
      environment:
        POSTGRES_DB: test_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432

  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: |
        python pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Run migrations
      run: poetry run python manage.py migrate

    - name: Run tests
      environment:
        DB_NAME=test_db
        DB_HOST=postgres
        DB_PORT=5432
        DB_USER=postgres
        DB_PASSWORD=postgres
      run: |
        poetry run python manage.py test

